version: '3.8'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    working_dir: /app/property_scraper
    command: tail -f /dev/null

  db:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_DB=property_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

  superset:
    image: amancevice/superset
    environment:
      - SUPERSET_SECRET_KEY= <YOUR SECRET KEY>
      - SUPERSET_LOAD_EXAMPLES=yes
      - SUPERSET_DATABASE_URI=postgresql://root:root@db:5432/property_db
      - SUPERSET_USERNAME=root
      - SUPERSET_PASSWORD=root
    ports:
      - "8088:8088"
    depends_on:
      - db
    volumes:
      - ./data/superset:/home/superset/.superset
  
  flask_api:
    build:
      context: .
      dockerfile: ./api/Dockerfile # Dockerfile for your API in the /api folder
    ports:
      - "5000:5000" # Expose the chosen port for accessing the API
    depends_on:
      - db # Specify the service name for your existing database container
